# bilinear interpolation of 2D image with scipy.ndimage

Reference:
* [scipy.ndimage.zoom()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.zoom.html)
* [Resampling a numpy array representing an image - stackoverflow](https://stackoverflow.com/questions/13242382/resampling-a-numpy-array-representing-an-image)

In [2]:
import numpy as np
import scipy.ndimage


In [4]:
x = np.arange(9).reshape(3,3)

In [6]:
print(f"original array:\n {x}")

original array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
print(f'Resampled by a factor of 2 with nearest interpolation:\n {scipy.ndimage.zoom(x, 2, order=0)}')

Resampled by a factor of 2 with nearest interpolation:
 [[0 0 1 1 2 2]
 [0 0 1 1 2 2]
 [3 3 4 4 5 5]
 [3 3 4 4 5 5]
 [6 6 7 7 8 8]
 [6 6 7 7 8 8]]


In [10]:
print(f'Resampled by a factor of 2 with bilinear interpolation:\n {scipy.ndimage.zoom(x, 2, order=1)}')

Resampled by a factor of 2 with bilinear interpolation:
 [[0 0 1 1 2 2]
 [1 2 2 2 3 3]
 [2 3 3 4 4 4]
 [4 4 4 5 5 6]
 [5 5 6 6 6 7]
 [6 6 7 7 8 8]]


In [11]:
print(f'Resampled by a factor of 2 with cubic interpolation:\n {scipy.ndimage.zoom(x, 2, order=3)}')

Resampled by a factor of 2 with cubic interpolation:
 [[0 0 1 1 2 2]
 [1 1 1 2 2 3]
 [2 2 3 3 4 4]
 [4 4 5 5 6 6]
 [5 6 6 7 7 7]
 [6 6 7 7 8 8]]
